// Code generated by protoc-gen-ecode v0.1, DO NOT EDIT.
// source: biohouse.proto

package biohouse

import (
	"github.com/bilibili/kratos/pkg/ecode"
)

// to suppressed 'imported but not used warning'
var _ ecode.Codes

// BiohouseErrCode ecode
var (
	PlayerNotExist              = ecode.New(1000)
	NotInTable                  = ecode.New(1001)
	EnterRoomIsClosing          = ecode.New(1002)
	CreatePlayerFailed          = ecode.New(1003)
	PlayerAlreadyLogin          = ecode.New(1004)
	InvalidToken                = ecode.New(1005)
	LoadPropsFailed             = ecode.New(1006)
	LoadUserInfoFailed          = ecode.New(1007)
	LoadGameDataFailed          = ecode.New(1008)
	EnterGameNotifyHall         = ecode.New(1009)
	EnterTableFailed            = ecode.New(1010)
	LimitRequireFailed          = ecode.New(1011)
	EnterLimit                  = ecode.New(1012)
	TokenVerifyFailed           = ecode.New(1013)
	TokenError                  = ecode.New(1014)
	ParameterIsWrong            = ecode.New(1015)
	MonsterNotExist             = ecode.New(1016)
	WeaponNotExist              = ecode.New(1017)
	MonsterHasKilled            = ecode.New(1018)
	MoneyNotEnough              = ecode.New(1019)
	PartHasDestroy              = ecode.New(1020)
	NotHasWeaponPart            = ecode.New(1021)
	WeaponPartUpgradeMax        = ecode.New(1022)
	WeaponPartNotFindUpgradeCfg = ecode.New(1023)
	UpgradeMaterialNotEnough    = ecode.New(1024)
	UpgradeMaterialNotFindCfg   = ecode.New(1025)
	HasReady                    = ecode.New(1026)
	MustEquipOneWeapon          = ecode.New(1027)
	PartQualityNotGreaterWeapon = ecode.New(1028)
	HandlNoWeapon               = ecode.New(1029)
	ZeroQualityUseDefaultRatio  = ecode.New(1030)
	RatioIllegal                = ecode.New(1031)
	RatioGreaterWeaponRatio     = ecode.New(1032)
	WeaponHurtIsZero            = ecode.New(1033)
	HasEnterTable               = ecode.New(1034)
	PartsHasDestroy             = ecode.New(1035)
	NoSkillCanUse               = ecode.New(1036)
	UseSkillIDIsError           = ecode.New(1037)
	ModeIsError                 = ecode.New(1038)
	PlayerHasDied               = ecode.New(1039)
	EnterTableMoneyNotEnough    = ecode.New(1040)
	EnterTableWeaponLevelNot    = ecode.New(1041)
	QPReadGoldFailed            = ecode.New(1042)
	QPEnterRoomFailed           = ecode.New(1043)
	VersionIsWrong              = ecode.New(1044)
	QPBaseUserInfoGetFailed     = ecode.New(1045)
)
