// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	pb "biohouse/api"
	"biohouse/internal/dao"
	// "biohouse/internal/server/http"
	"biohouse/internal/server/tcp"
	"biohouse/internal/service"

	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	daoDao, err := dao.New()
	if err != nil {
		return nil, nil, err
	}
	serviceService, err := service.New(daoDao)
	if err != nil {
		return nil, nil, err
	}
	// engine, err := http.New(serviceService)
	// if err != nil {
	// 	return nil, nil, err
	// }
	server, err := tcp.New(serviceService)
	if err != nil {
		return nil, nil, err
	}
	app, cleanup, err := NewApp(serviceService, server)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:
var daoProvider = wire.NewSet(dao.New)
var serviceProvider = wire.NewSet(service.New, wire.Bind(new(pb.BiohouseCometServer), new(*service.Service)))
